TEST_NAMES = char_utils GridSize hash_namify keyname_utils MemoryFactory StaticString SolveState String string_utils timing TypeTracker unique value_utils
TEST_DIR = $(CURDIR)

include ../Makefile-tests.mk
