
language: python

env:
  - SPHINX_VERSION=1.2.3 TRAVIS_CI=True
  - SPHINX_VERSION=1.3.1 TRAVIS_CI=True

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y doxygen texlive-latex-base texlive-latex-extra texlive-fonts-recommended

install:
  - pip install flake8
  - pip install nose
  - pip install Sphinx==$SPHINX_VERSION
  - pip install .

# Builds all examples & html documentation
#
# Provide definition for DOXYGEN variable to stop it trying
# to run `which doxygen`
script:
  - make DOXYGEN=doxygen DEBUG=""
  - make tests
  - make flake8

