test: test.cc QuorumOrg.h QuorumManager.h PopulationManager.h
	g++ -std=c++11 test.cc -o test.out
debug: test.cc QuorumOrg.h QuorumManager.h PopulationManager.h
	g++ -std=c++11 -g test.cc -o test.debug

clean:
	rm -rf ./a.out
	rm -rf ./test.out
	rm -rf ./test.debug
