#!/usr/bin/env python

import sys

with open(sys.argv[1]) as infile:
    open_braces = 0
    bracket_counts = []
    for line in infile:
        line = line.strip()
        if line.startswith("namespace emp {") or \
           line.startswith("namespace web {") or \
           line.startswith("namespace prefab {") or \
           line.startswith("namespace emp::prefab {") or \
           line.startswith("namespace evo {"):
            open_braces += 1
            bracket_counts.append(open_braces)
            print()
        elif bracket_counts and bracket_counts[-1] == open_braces and line == "}":
            print()
            open_braces -= 1
            bracket_counts.pop()
        else:
            if bracket_counts:
                open_braces += line.count("{")
                open_braces -= line.count("}")
            line = line.replace("emp::", "")
            line = line.replace("web::", "")
            line = line.replace("prefab::", "")
            print(line)
