TEST_DIR = datatructs
TEST_NAMES = BloomFilter Bool Cache DynamicString Graph graph_utils hash_utils IndexMap map_utils QueueCache ra_map ra_set reference_vector RobinHoodMap set_utils SmallFifoMap SmallVector StaticVector StringMap TimeQueue tuple_struct tuple_utils TypeMap UnorderedIndexMap valsort_map Vector vector_utils

include ../Makefile-tests.mk
