clean:
	# $(MAKE) clean -C EasyChair/
	$(MAKE) clean -C MAP-Elites-Arm/
	$(MAKE) clean -C NK/
	$(MAKE) clean -C SelectionAnalyze/
	$(MAKE) clean -C SpatialCoop2017/
	$(MAKE) clean -C Sudoku/
	# $(MAKE) clean -C utils/
