
othello: AvidaGP-Othello.cc
	g++ AvidaGP-Othello.cc -O3 --std=c++14 -I ../source -o othelloGP

debug: AvidaGP-Othello.cc
	g++ AvidaGP-Othello.cc -g --std=c++14 -I ../source -o othelloDB

clean:
	rm *.o othelloGP
